### ISSUE TITLE
no new token generated for each requests

### ISSUE THREAD

**Issue by exenza** [volnix/csrf#5]
When a request is submitted and validated the same token is used for new requests.

I've changed line 72 which was originally only returning a boolean and I'm generating a new token if the original one is consumed:

			if(static::compare($request_data[$token_name], static::getToken($token_name))){
				static::generateToken($token_name);
				return true;
			} else {
				return false;
			}

**Comment by volnix** [comment]
Makes sense.  Good catch!  Feel free to submit a PR and I'll approve/merge.

**Comment by exenza** [comment]
Done, here the PR: https://github.com/volnix/csrf/pull/6

**Comment by ridaamirini** [comment]
PLS MERGE :+1:

**Comment by ridaamirini** [comment]
But whats about if i have three forms opened at the same time and i one of them get submitted ? The token is consumed by the first submitted form but whats about the two other forms with the same token they are invalid afterwards.

**Comment by ridaamirini** [comment]
See https://security.stackexchange.com/a/22936
